### ISSUE TITLE
[zaffre.glterminal] - Error executing terminal fn

### ISSUE THREAD

**Issue by owenmpierce** [aaron-santos/zaffre#7]
Hello,

I am trying to use zaffre as a dependency in a new project that I created with lein.  I tried to run the example code that is in the Quickstart, but I am met with an error.

[project.clj](http://pastebin.com/6mA5SKPp)
[core.clj](http://pastebin.com/cy7H8H4z)
[error printed to console after starting with lein run](http://pastebin.com/dWLhueUX)

Do you know what I am doing wrong?  I was able to run the examples in this repository without problem.

Owen

**Comment by aaron-santos** [comment]
Hi Owen,

Good catch! I forgot to update readme after a change to the do-frame macro. Try changing 

    (zat/do-frame 33 (zat/clear! terminal) ))))

to 

    (zat/do-frame terminal 33 (zat/clear! terminal) ))))

I'll also point out that the do-frame macro calls [clear and refresh](https://github.com/aaron-santos/zaffre/blob/feabb70030bf75084b8836cecf08c26099aec725/src/zaffre/terminal.cljc#L32) so you can omit those calls if you like. :)

**Comment by owenmpierce** [comment]
That fixes it, thank you.
